server:
  port: 8181

spring:
 datasource:
   url: jdbc:mysql://localhost:3306/microservicios
   username: root
   password:
   driver: com.mysql.cj.jdbc.Driver
      
jpa:
 hibernate:
 ddl-auto:
 show-sql: true
 properties:
  hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect	